### ISSUE TITLE
Compile issues on  nightly

### ISSUE THREAD

**Issue by BaxterEaves** [sebcrozet/nalgebra#369]
Updated nightly this morning and rebuilt a package that has nalgebra as a dependency and I got a lot of `not found` type compile errors:

```
 Compiling nalgebra v0.16.0
error[E0432]: unresolved import `geometry::Isometry`
  --> /Users/baxtereaves/.cargo/registry/src/github.com-1ecc6299db9ec823/nalgebra-0.16.0/src/base/cg.rs:15:16
   |
15 | use geometry::{Isometry, IsometryMatrix3, Orthographic3, Perspective3, Point, Point3, Rotation2,
   |                ^^^^^^^^ no `Isometry` in `geometry`. Did you mean to use `isometry`?

error[E0432]: unresolved import `geometry::Isometry`
  --> /Users/baxtereaves/.cargo/registry/src/github.com-1ecc6299db9ec823/nalgebra-0.16.0/src/geometry/rotation_conversion.rs:13:16
   |
13 | use geometry::{Isometry, Point, Rotation, Rotation2, Rotation3, Similarity, SuperTCategoryOf,
   |                ^^^^^^^^ no `Isometry` in `geometry`. Did you mean to use `isometry`?

error[E0432]: unresolved import `geometry::Similarity`
  --> /Users/baxtereaves/.cargo/registry/src/github.com-1ecc6299db9ec823/nalgebra-0.16.0/src/geometry/rotation_conversion.rs:13:65
   |
13 | use geometry::{Isometry, Point, Rotation, Rotation2, Rotation3, Similarity, SuperTCategoryOf,
   |                                                                 ^^^^^^^^^^ no `Similarity` in `geometry`. Did you mean to use `similarity`?

error[E0432]: unresolved import `geometry::Isometry`
  --> /Users/baxtereaves/.cargo/registry/src/github.com-1ecc6299db9ec823/nalgebra-0.16.0/src/geometry/quaternion_conversion.rs:11:16
   |
11 | use geometry::{Isometry, Point3, Quaternion, Rotation, Rotation3, Similarity, SuperTCategoryOf,
   |                ^^^^^^^^ no `Isometry` in `geometry`. Did you mean to use `isometry`?

error[E0432]: unresolved import `geometry::Similarity`
  --> /Users/baxtereaves/.cargo/registry/src/github.com-1ecc6299db9ec823/nalgebra-0.16.0/src/geometry/quaternion_conversion.rs:11:67
   |
11 | use geometry::{Isometry, Point3, Quaternion, Rotation, Rotation3, Similarity, SuperTCategoryOf,
   |                                                                   ^^^^^^^^^^ no `Similarity` in `geometry`. Did you mean to use `similarity`?

error[E0432]: unresolved import `geometry::Isometry`
 --> /Users/baxtereaves/.cargo/registry/src/github.com-1ecc6299db9ec823/nalgebra-0.16.0/src/geometry/unit_complex_ops.rs:9:16
  |
9 | use geometry::{Isometry, Point2, Rotation, Similarity, Translation, UnitComplex};
  |                ^^^^^^^^ no `Isometry` in `geometry`. Did you mean to use `isometry`?

```

...and so on. I've left a lot out because it was super long. I reverted back to the previous toolchain that i was using, `nightly-2018-08-15-x86_64-apple-darwin`, and it worked.

**NOTE**: I successfully compiled the code on my gitlab CI, which is using the nightly image, so it might be a problem with the apple toolchain.

**EDIT**: Actually, the nightly docker image hadn't been pushed yet. Now my CI is broken as well.

**Comment by Lecrapouille** [comment]
I've the same problem (unresolved import `geometry::Isometry`) on Debian (amd64). I'm a total newbie with Rust. I installed it with: `curl -s https://static.rust-lang.org/rustup.sh | sh -s -- --channel=nightly`

**Comment by sebcrozet** [comment]
This issue looks like a regression on the nightly compiler. However, it does compile correctly on my machine (MacOS) with the latest nightly: rustc 1.30.0-nightly (33b923fd4 2018-08-18)

@Lecrapouille What project exactly are you compiling? Can you try cloning the nalgebra repo and compiling it alone? I have the same compiler version as you but manage to compile nalgebra just fine, so I am not sure how to reproduce the errors.

**Comment by Lecrapouille** [comment]
@sebcrozet I cloned your master branch and compiled it with success :) So sorry for the confusion, what I wanted to said is that I got failure with [this project](https://github.com/citybound/citybound) and I saw this issue. I've just started learning Rust since yesterday so maybe I made something wrong.

**Comment by sebcrozet** [comment]
I still have not found the cause of those errors.

@BaxterEaves What package depending on nalgebra did you try to compile?

@Lecrapouille I can reproduce the compile errors by compiling citybounds. That looks like a regression on the rust compiler but I failed to identify it source. Here is the dependency graph of citybound generated by `cargo graph`:

![deps](https://user-images.githubusercontent.com/1734958/44624869-861ae500-a8fa-11e8-90d8-9c9c36cd9a98.png)

I tried to compile individually the `game_common` crate but it fails with the same errors. However, compiling any of its dependency that depend themselves on nalgebra (namely `descartes` and `michelangelo`) do succeed.

I guess the best workaround for now is to just revert the compiler version like @BaxterEaves did…

**Comment by Lecrapouille** [comment]
@sebcrozet just to let you know that I followed their .travis.yml file and the compilation passed :)

**Comment by BaxterEaves** [comment]
@sebcrozet Here is the dependency graph for my `rv` crate that is experiencing the issues.
![rainbow-graph](https://user-images.githubusercontent.com/1041591/44791400-28d79b80-ab67-11e8-823e-412a3a5e5f8a.png)

**Comment by Lecrapouille** [comment]
@BaxterEaves in my previous post I did not thank you for your fast answer: so thank you ! 

This is just a noob remark, but if these dependencies are similar to C/C++ with their #includes, having your dependencies looking a graph is not a good thing to have because depending on how to traverse the graph, the order of inclusion can be different and therefore getting problem like defining struct after another (instead of before as you were expected first). Cannot you reduce your graph to a minimum spanning tree ? (for example removing the link rv --> serve, num -->num-bigint).

**Comment by BaxterEaves** [comment]
Just some extra info: I tried to clone and compile master with most recent nightly. `cargo build` works, but `cargo build --features serde-serialize` fails with the above errors.

**Comment by sebcrozet** [comment]
@Lecrapouille  Rust dependencies are not similar to C/C++ includes so having a graph does not cause any issue of redefinition. In fact the Rust compiler really doesn't really care about on what order things are declared on a single crate.

@BaxterEaves Thank you for your inputs. The failure only when serde is enabled is troubling though.

**Comment by robsmith11** [comment]
My crate produced these errors as well when using nightly-2018-09-02 and the serde feature.  Disabling the serde feature makes it work.

**Comment by sebcrozet** [comment]
It appears the errors at the root of this problem are similar to:

```
error: cannot determine resolution for the attribute macro `serde`
 --> src/isometry.rs:7:3
  |
7 | #[serde(bound(serialize = ""))]
  |   ^^^^^
  |
  = note: import resolution is stuck, try simplifying macro imports
```

which can be reproduced with:

```rust
use serde;

/// A direct isometry, i.e., a rotation followed by a translation.
#[repr(C)]
#[derive(Debug)]
#[cfg_attr(feature = "serde-serialize", derive(Serialize, Deserialize))]
#[serde(bound(serialize = ""))]
#[serde(bound(deserialize = ""))]
pub struct Isometry
{
}
```

This is likely related to https://github.com/rust-lang/rust/issues/53675 which is a known but not-yet-fixed regression.

A workaround seems to avoid the `use serde;` by importing all the required serde struct explicitly.
