### ISSUE TITLE
Can't implement Index for Vector3 but works for Point3 since 0.13

### ISSUE THREAD

**Issue by svenstaro** [sebcrozet/nalgebra#319]
I just upgraded my nalgebra 0.12 codebase to 0.14 and noticed that starting with 0.13 my build starts failing with this error:

> error[E0210]: type parameter `<nalgebra::DefaultAllocator as nalgebra::allocator::Allocator<f32, nalgebra::U3>>::Buffer` must be used as the type parameter for some local type (e.g. `MyStruct<T>`); only traits defined in the current crate can be implemented for a type parameter

I have this:

```rust
#[derive(Debug, Copy, Clone, PartialEq)]
pub enum Axis {
    /// Index of the X axis.
    X = 0,

    /// Index of the Y axis.
    Y = 1,

    /// Index of the Z axis.
    Z = 2,
}

// This works:
impl Index<Axis> for Point3<f32> {
    type Output = f32;

    fn index(&self, axis: Axis) -> &f32 {
        match axis {
            Axis::X => &self.x,
            Axis::Y => &self.y,
            Axis::Z => &self.z,
        }
    }
}

// This now fails but used to work:
impl Index<Axis> for Vector3<f32> {
    type Output = f32;

    fn index(&self, axis: Axis) -> &f32 {
        match axis {
            Axis::X => &self.x,
            Axis::Y => &self.y,
            Axis::Z => &self.z,
        }
    }
}
```

**Comment by sebcrozet** [comment]
Unfortunately, this seems to be a bug in the compiler. See https://github.com/rust-lang/rust/issues/46210. This used to work in the version 0.12 because the `Vector3<f32>` was an alias for: `Matrix<f32, U3, U1, MatrixArray<f32, U3, U1>>`. It no longer works now because the the last type parameter `MatrixArray<f32, U3, U1>` has been replaced by an associated type.

A work-around would be to implement `Index<Axis>` for `Matrix<f32, U3, U1, MatrixArray<f32, U3, U1>>`. I'll have to think more about it to see if there is an other way.
